const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

console.log('=== TEST: INDUSTRY EQUIPMENT IMPORT, TOOLBAR LAYOUT & RECON BADGE FIX ===');

const invHtml = fs.readFileSync(path.join(__dirname, '../carbon-inventory.html'), 'utf8');
const actJs = fs.readFileSync(path.join(__dirname, '../assets/js/carbon-activity.js'), 'utf8');
const dashJs = fs.readFileSync(path.join(__dirname, '../assets/js/carbon-dashboard.js'), 'utf8');
const eqDbJs = fs.readFileSync(path.join(__dirname, '../assets/js/equipment-db.js'), 'utf8');

// 1. Kiểm tra loại bỏ chữ "100% Khớp" trên nút Đối soát thiết bị
assert.ok(!invHtml.includes('>100% Khớp</span>'), 'HTML không được chứa badge >100% Khớp</span> trên thanh công cụ');
assert.ok(invHtml.includes("btnReview.innerHTML = '<span>Đối soát thiết bị</span>';"),
  'updateEquipmentReconciliationBadge phải gán nhãn nút Đối soát thiết bị tinh gọn khi không có lỗi');
console.log('PASS 1: Đã loại bỏ hoàn toàn chữ 100% Khớp khỏi nút Đối soát thiết bị.');

// 2. Kiểm tra giao diện thanh công cụ: Tránh đè lên nút Tải file mẫu
assert.ok(invHtml.includes('max-width: 400px;'),
  '.custom-select-container CSS phải có max-width để không tràn thanh công cụ');
assert.ok(invHtml.includes('flex-wrap: wrap;'),
  'Cụm nút công cụ thiết bị phải có flex-wrap: wrap;');
console.log('PASS 2: Thanh công cụ đã cấu hình co giãn flex-wrap và giới hạn max-width chống tràn/đè.');

// 3. Kiểm tra cơ chế nén và giải mã nhật ký hoạt động lớn (Xi măng / Phân bón > 40 thiết bị)
const store = {
  'gs_current_user': 'Hi, Phạm Ngọc Vinh'
};

const sandbox = {
  console,
  localStorage: {
    getItem: (k) => (k in store ? store[k] : null),
    setItem: (k, v) => { store[k] = String(v); },
    removeItem: (k) => { delete store[k]; },
    clear: () => { Object.keys(store).forEach(k => delete store[k]); },
    key: (i) => Object.keys(store)[i],
    get length() { return Object.keys(store).length; }
  },
  getBranchStorageKey: (type) => {
    return 'gs_data_hi_pham_ngoc_vinh_tru_so_chinh_' + type;
  },
  normalizeConsumptionUnit: (u) => u || 'kWh',
  lookupFactor: (ef) => ({ factor: 0.6766, fuelItem: null }),
  isVnPublicHoliday: () => false,
  confirm: () => true
};

sandbox.window = sandbox;
sandbox.window.addEventListener = () => {};

function createMockEl() {
  return {
    value: '', innerHTML: '', innerText: '', style: {}, dataset: {},
    addEventListener: () => {}, removeEventListener: () => {}, appendChild: () => {},
    remove: () => {}, querySelectorAll: () => [], querySelector: () => null,
    closest: () => null, classList: { add: () => {}, remove: () => {}, contains: () => false }
  };
}

const domElements = {
  'branch-selector': { ...createMockEl(), value: 'Trụ sở chính' },
  'act-filter-year': { ...createMockEl(), value: '2026' },
  'act-filter-month': { ...createMockEl(), value: 'all' },
  'act-hidden-filter': { ...createMockEl(), value: 'all' },
  'activity-tbody': { ...createMockEl(), innerHTML: '', querySelectorAll: () => [] },
  'machine-overview-tbody': { ...createMockEl() },
  'recon-summary-tbody': { ...createMockEl() },
  'no-activity-row': { ...createMockEl() }
};

sandbox.document = {
  getElementById: (id) => domElements[id] || createMockEl(),
  querySelectorAll: () => [],
  createElement: () => createMockEl(),
  createDocumentFragment: () => ({
    appendChild: () => {}
  }),
  addEventListener: () => {}
};

vm.createContext(sandbox);
vm.runInContext(eqDbJs, sandbox);
vm.runInContext(actJs, sandbox);

// Giả lập nhập 44 thiết bị Phân bón
const fertEqs = sandbox.window.getIndustryEquipments('Phân bón');
assert.strictEqual(fertEqs.length, 44, 'Phân bón phải có đúng 44 thiết bị mẫu chuẩn');

const sources = fertEqs.map((eq, idx) => ({
  id: 'src_' + idx,
  category: eq.energyType === 'ELECTRICITY' ? 'Tiêu thụ điện' : 'Đốt cháy cố định',
  type: eq.name,
  eq: eq.name,
  eqAsset: eq.code,
  ef: eq.energyType === 'ELECTRICITY' ? 'Điện lưới Việt Nam' : 'Khí tự nhiên (NG)',
  efFactor: '0.6766',
  efUnit: 'kgCO2e/kWh',
  measure: 'Ước tính công suất',
  opCapacity: (eq.ratedCapacity || 45).toString(),
  opCapUnit: eq.capacityUnit || 'kW',
  opLoad: '80',
  opHoursDay: (eq.code && (eq.code.includes('GENSET') || eq.code.includes('FIRE-PUMP'))) ? '2' : '16',
  opDaysWeek: (eq.code && (eq.code.includes('GENSET') || eq.code.includes('FIRE-PUMP'))) ? '1' : '6',
  hourlyRate: (eq.ratedCapacity || 45) * 0.8,
  annualEstQty: (eq.ratedCapacity || 45) * 0.8 * 16 * 6 * 52,
  annualEstEmissions: 1000
}));

const srcKey = sandbox.getBranchStorageKey('sources');
const actKey = sandbox.getBranchStorageKey('activity');
store[srcKey] = JSON.stringify(sources);

// Tự động phân bổ ca máy
const createdCount = sandbox.window.autoGenerateDailyOperationalRecords('2026', 'all', false);
assert.ok(createdCount > 0, `Phải tạo thành công bản ghi ca máy, thực tế: ${createdCount}`);
assert.ok(store[actKey], 'Dữ liệu hoạt động phải được lưu vào localStorage');

// Kiểm tra dung lượng lưu trữ nằm an toàn trong quota (< 4.5MB)
const storedBytes = store[actKey].length;
const storedMB = storedBytes / 1024 / 1024;
console.log(`Dung lượng dữ liệu hoạt động sau khi lưu: ${storedMB.toFixed(2)} MB (${createdCount} bản ghi)`);
assert.ok(storedMB < 4.5, `Dung lượng lưu trữ (${storedMB.toFixed(2)} MB) phải nhỏ hơn 4.5MB để tránh tràn quota`);

console.log('PASS 3: Tự động phân bổ và lưu an toàn toàn bộ 44 thiết bị mà không gặp QuotaExceededError.');

// 4. Kiểm tra loadActivityList và giải mã dữ liệu sau F5
sandbox.window.loadActivityList();
const parsedActs = JSON.parse(store[actKey]);
const decodedActs = (typeof sandbox.window.decodeActivitiesData === 'function') 
  ? sandbox.window.decodeActivitiesData(parsedActs)
  : parsedActs;

assert.ok(decodedActs.length > 0, 'Dữ liệu hoạt động sau khi đọc phải có bản ghi, không bị trống');
assert.ok(decodedActs[0].date && decodedActs[0].sourceName && decodedActs[0].amount,
  'Bản ghi giải mã phải bảo toàn đầy đủ trường date, sourceName, amount');

console.log('PASS 4: loadActivityList đọc và giải mã chính xác dữ liệu sau F5.');

console.log('\n=== TẤT CẢ CÁC BÀI TEST IMPORT THIẾT BỊ VÀ THANH CÔNG CỤ ĐÃ ĐẠT 100%! ===');
