const fs = require('fs');
const assert = require('assert');

console.log('Running test_recon_machine_sources_and_unit_norm.js...');

const actJs = fs.readFileSync('assets/js/carbon-activity.js', 'utf8');

// 1. Verify getMachineSources helper is present
assert(actJs.includes('function getMachineSources()'), 'getMachineSources must be declared as a shared helper function');

// 2. Verify renderReconciliationSummary invokes getMachineSources
const reconStart = actJs.indexOf('function renderReconciliationSummary()');
const reconEnd = actJs.indexOf('function autoGenerateMonthlyOperationalRecords');
assert(reconStart !== -1 && reconEnd !== -1, 'Both functions must exist');
const reconBody = actJs.substring(reconStart, reconEnd);
assert(reconBody.includes('getMachineSources()'), 'renderReconciliationSummary must call getMachineSources() to prevent ReferenceError');

// 3. Verify renderMachineOverview invokes getMachineSources
const overviewStart = actJs.indexOf('function renderMachineOverview()');
const overviewEnd = actJs.indexOf('function renderReconciliationSummary()');
const overviewBody = actJs.substring(overviewStart, overviewEnd);
assert(overviewBody.includes('getMachineSources()'), 'renderMachineOverview must call getMachineSources()');

// 4. Verify autoGenerateDailyOperationalRecords normalizes consumption units
const dailyStart = actJs.indexOf('function autoGenerateDailyOperationalRecords');
const dailyEnd = actJs.indexOf('window.autoGenerateDailyOperationalRecords');
const dailyBody = actJs.substring(dailyStart, dailyEnd);
assert(dailyBody.includes('normalizeConsumptionUnit(rawUnit, src.type)'), 'autoGenerateDailyOperationalRecords must normalize consumption units');

// 5. Simulate getMachineSources logic
const mockSources = [
    { measure: 'Tự đánh giá', opCapacity: '45', opCapUnit: 'kW', opLoad: '80', hourlyRate: '36', opHoursDay: '16', opDaysWeek: '6', type: 'Chiller', eq: 'Chiller A' },
    { measure: 'Tự đánh giá', opCapacity: '50', opCapUnit: 'lít/h', opLoad: '70', hourlyRate: '35', opHoursDay: '8', opDaysWeek: '5', type: 'Lò hơi', eq: 'Lò hơi 1' }
];

const parsed = mockSources.map(src => {
    const measure = src.measure || '';
    const opCap = parseFloat(src.opCapacity) || 0;
    const loadVal = parseFloat(src.opLoad) || 80;
    const hRate = parseFloat(src.hourlyRate) || (opCap > 0 ? Math.round(opCap * (loadVal / 100) * 1000) / 1000 : 0);
    return {
        name: src.eq,
        capacity: opCap,
        load: loadVal,
        hourlyRate: hRate
    };
});

assert.strictEqual(parsed.length, 2);
assert.strictEqual(parsed[0].hourlyRate, 36);
assert.strictEqual(parsed[1].hourlyRate, 35);

console.log('PASSED: test_recon_machine_sources_and_unit_norm.js');
