const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

console.log('================================================================');
console.log('KIEM THU: KHAC PHUC TRIET DE CHUA PHAN LOAI, IPPU UNIT & DOI SOAT');
console.log('================================================================');

const actJs = fs.readFileSync(path.join(__dirname, '..', 'assets', 'js', 'carbon-activity.js'), 'utf8');
const dashJs = fs.readFileSync(path.join(__dirname, '..', 'assets', 'js', 'carbon-dashboard.js'), 'utf8');
const invHtml = fs.readFileSync(path.join(__dirname, '..', 'carbon-inventory.html'), 'utf8');

// 1. Quy tac ZERO EMOJI tuyet doi
const emojiRegex = /[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F1E6}-\u{1F1FF}]/u;
assert.ok(!emojiRegex.test(actJs), 'carbon-activity.js khong duoc chua emoji');
assert.ok(!emojiRegex.test(dashJs), 'carbon-dashboard.js khong duoc chua emoji');
assert.ok(!emojiRegex.test(invHtml), 'carbon-inventory.html khong duoc chua emoji');
console.log('PASS 1: Quy tac ZERO EMOJI tren toan bo ma nguon.');

// 2. Kiem tra CATEGORY_SCOPE trong carbon-dashboard.js
assert.ok(dashJs.includes("'Đốt cháy sinh khối (Biogenic)': 1"), 'CATEGORY_SCOPE phai co Đốt cháy sinh khối (Biogenic)');
assert.ok(dashJs.includes("'Phát thải rò rỉ': 1"), 'CATEGORY_SCOPE phai co Phát thải rò rỉ');
assert.ok(dashJs.includes("'Xử lý chất thải / Nước thải': 1"), 'CATEGORY_SCOPE phai co Xử lý chất thải / Nước thải');
assert.ok(dashJs.includes("'Quá trình công nghiệp': 1"), 'CATEGORY_SCOPE phai co Quá trình công nghiệp');
assert.ok(dashJs.includes("'IPPU': 1"), 'CATEGORY_SCOPE phai co IPPU');
console.log('PASS 2: CATEGORY_SCOPE ho tro 100% cac danh muc phat thai Scope 1 dac thu.');

// 3. Kiem tra normalizeConsumptionUnit chan tuyet doi kWh cho IPPU
assert.ok(actJs.includes('quá trình thổi oxy') || actJs.includes('thổi oxy'), 'normalizeConsumptionUnit phai nhan dien thoi oxy');
assert.ok(actJs.includes('luyện thép'), 'normalizeConsumptionUnit phai nhan dien luyen thep');
assert.ok(actJs.includes("if (u.includes('kwh') || u.includes('kw')) return 'tấn'"), 'normalizeConsumptionUnit phai ep don vi kWh ve tan cho IPPU');
console.log('PASS 3: normalizeConsumptionUnit chan tuyet doi don vi kWh cho nguon IPPU.');

// 4. Kiem tra autoGenerateDailyOperationalRecords luu category day du
assert.ok(actJs.includes("category: src.category || (isProc ? 'Các quá trình công nghiệp'"), 'autoGenerateDailyOperationalRecords phai luu category');
assert.ok(actJs.includes("fuel: src.ef || ''"), 'autoGenerateDailyOperationalRecords phai luu fuel');
assert.ok(actJs.includes("ef: src.ef || ''"), 'autoGenerateDailyOperationalRecords phai luu ef');
console.log('PASS 4: autoGenerateDailyOperationalRecords luu tru category, fuel, ef day du vao localStorage.');

// 5. Kiem tra carbon-inventory.html khong con loi Assignment to constant variable
assert.ok(invHtml.includes('let activities = [];'), 'seedIndustrySampleData phai khai bao let activities = [];');
assert.ok(!invHtml.includes('const activities = [];\n      for (let m = 1; m <= 12; m++)'), 'Khong duoc dung const activities khi co gan lai activities = generatedActs');
console.log('PASS 5: seedIndustrySampleData sua loi TypeError: Assignment to constant variable.');

// 6. Kiem tra thong bao va can chinh chu ky doi soat trong renderReconciliationSummary
assert.ok(actJs.includes('recon-period-notice'), 'renderReconciliationSummary phai cap nhat thong bao recon-period-notice');
assert.ok(actJs.includes('invoiceMonths.length === 1 && !isMonth'), 'renderReconciliationSummary phai nhan dien hoa don 1 thang');
assert.ok(invHtml.includes('id="recon-period-notice"'), 'carbon-inventory.html phai co the div recon-period-notice');
console.log('PASS 6: Doi soat Ke toan vs Ky su tu dong nhan dien chu ky hoa don va hien thi thong bao ro rang.');

console.log('================================================================');
console.log('TAT CA 6 MUC KIEM THU DA HOAN THANH VA CHINH XAC 100%!');
console.log('================================================================');
