const fs = require('fs');
const path = require('path');
const assert = require('assert');

console.log('=== TEST: DAILY OPERATIONAL BREAKDOWN (FULL DAYS IN MONTH) ===');

// 1. Verify HTML UI
const html = fs.readFileSync(path.join(__dirname, '..', 'carbon-inventory.html'), 'utf8');
assert(!html.includes('id="btn-auto-schedule-daily"'), 'btn-auto-schedule-daily removed per user request (daily is now system default)');
assert(!html.includes('id="btn-auto-schedule-baseline"'), 'btn-auto-schedule-baseline removed per user request');
console.log('PASS 1: UI button removed and daily breakdown is now the system default.');

// 2. Verify JS implementation
const js = fs.readFileSync(path.join(__dirname, '..', 'assets', 'js', 'carbon-activity.js'), 'utf8');
assert(js.includes('autoGenerateDailyOperationalRecords'), 'autoGenerateDailyOperationalRecords must exist in carbon-activity.js');
assert(js.includes('btn-auto-schedule-daily'), 'btn-auto-schedule-daily event listener must be bound');
console.log('PASS 2: Function and event binding exist in JS.');

// 3. Test calculation logic of Daily Operational Distribution for Jan 2026
const year = '2026';
const month = 1; // January
const isLeapYear = false;
const daysInJan = 31;

// Equipment: Xe nâng hàng 3.5 tấn: 3 lít/h, 8h/ngày, 6 ngày/tuần (Nghỉ Chủ nhật)
const machine = {
  name: 'Xe nâng hàng 3.5 tấn',
  hourlyRate: 3,
  opHoursDay: 8,
  opDaysWeek: 6,
  efFactor: 2.6853
};

const dailyQty = machine.hourlyRate * machine.opHoursDay; // 24 lít/ngày
assert.strictEqual(dailyQty, 24, 'Daily run must be 24 liters/day');

const records = [];
for (let d = 1; d <= daysInJan; d++) {
  const dateObj = new Date(parseInt(year), month - 1, d);
  const dayOfWeek = dateObj.getDay();
  if (machine.opDaysWeek === 6 && dayOfWeek === 0) continue; // Skip Sunday

  const mStr = String(month).padStart(2, '0');
  const dStr = String(d).padStart(2, '0');
  records.push({
    date: `${year}-${mStr}-${dStr}`,
    sourceName: machine.name,
    amount: dailyQty,
    doc: `Vận hành ca ngày (${machine.opHoursDay}h/ngày)`,
    entryMode: 'auto_daily'
  });
}

// In January 2026, Sundays are: Jan 4, Jan 11, Jan 18, Jan 25 (4 Sundays)
// 31 - 4 = 27 working days
assert.strictEqual(records.length, 27, 'January 2026 must have exactly 27 working day records');
assert.strictEqual(records[0].date, '2026-01-01', 'First record must be 2026-01-01');
assert.strictEqual(records[1].date, '2026-01-02', 'Second record must be 2026-01-02');
assert.strictEqual(records[2].date, '2026-01-03', 'Third record must be 2026-01-03');
assert.strictEqual(records[3].date, '2026-01-05', 'Fourth record must be 2026-01-05 (Jan 4 Sunday skipped)');
assert.strictEqual(records[26].date, '2026-01-31', 'Last record must be 2026-01-31');

console.log('PASS 3: Daily generation creates all working days in the month correctly (27 days generated, Sundays skipped).');

// 4. Verify month filter matches all 27 records
const filterMonth = '01';
const matchedRecords = records.filter(r => r.date.split('-')[1] === filterMonth);
assert.strictEqual(matchedRecords.length, 27, 'Month 01 filter must match all 27 daily records');
console.log('PASS 4: Month filter displays all daily records in the month seamlessly.');

console.log('\nALL DAILY BREAKDOWN CHECKS PASSED 100%!');
